### ISSUE TITLE
Problem with `unlink()` and `chmod()` on nonexistent files

### ISSUE THREAD

**Issue by zigu007** [laminas/laminas-cache-storage-adapter-filesystem#6]
Hi! I have such errors:
```
[04-Jan-2021 21:27:02 Europe/Warsaw] PHP Warning:  unlink(/home/users/default/public_html/PRIVATE/data/cache/laminascache-5a/laminascache--d751713988987e9331980363e24189ce.tag): No such file or directory in /home/users/default/public_html/PRIVATE/vendor/laminas/laminas-cache-storage-adapter-filesystem/src/Filesystem.php on line 412
[05-Jan-2021 13:01:22 Europe/Warsaw] PHP Fatal error:  Uncaught ErrorException: chmod(): No such file or directory in /home/users/default/public_html/PRIVATE/vendor/laminas/laminas-cache-storage-adapter-filesystem/src/Filesystem.php:1638
Stack trace:
#0 [internal function]: Laminas\Stdlib\ErrorHandler::addError(2, 'chmod(): No suc...', '/home/users/def...', 1638, Array)
#1 /home/users/default/public_html/PRIVATE/vendor/laminas/laminas-cache-storage-adapter-filesystem/src/Filesystem.php(1638): chmod('/home/users/def...', 384)
#2 /home/users/default/public_html/PRIVATE/vendor/laminas/laminas-cache-storage-adapter-filesystem/src/Filesystem.php(337): Laminas\Cache\Storage\Adapter\Filesystem->putFileContent('/home/users/def...', 'PicturesTS\nPict...')
#3 /home/users/default/public_html/PRIVATE/module/CoreTS/src/Model/TsCache.php(0): Laminas\Cache\Storage\Adapter\Filesystem->setTags('PicturesTS_Pict...', Array)
#4 /home/users/default/public_html/PRIVATE/module/CoreTS/src/Model/TsBaseModel.php(0): CoreTS\Model\TsCache->saveCache(Object(Propel\Runtime in /home/users/default/public_html/PRIVATE/vendor/laminas/laminas-cache-storage-adapter-filesystem/src/Filesystem.php on line 1641
```
Probably caused by too fast / multiple cache cleaning.

Does this code: https://github.com/laminas/laminas-cache-storage-adapter-filesystem/blob/aa56c2ee326aa1b4b44d2e9ee6dbc35976990e01/src/Filesystem.php#L412

...should look like this:
```
if (file_exists($pathname)) {
    unlink($pathname);
}
```

To prevent code errors like this?

**Comment by Ocramius** [comment]
That still doesn't guarantee no error, since two processes performing deletion at the same time can run in a race condition.

Probably best to delete and ignore any errors explicitly.

**Comment by boesing** [comment]
I'll target 2.0 milestone for this and applying it there.
There is no ETA regarding v2.0 but the filesystem adapter is most likely to be adopted to laminas-cache 3.0.
